# SecretProviderClass update (add secretObjects)
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-manager
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: my-secret
        objectType: secretsmanager
  secretObjects:
    - secretName: aws-secret-synced
      type: Opaque
      data:
        - objectName: my-secret
          key: password
---
# Pod consuming the synced Secret
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: my-image
    env:
    - name: MY_PASSWORD
      valueFrom:
        secretKeyRef:
          name: aws-secret-synced
          key: password
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secrets
  volumes:
  - name: secret-volume
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "aws-secrets-manager"