name: "CVEs Docker Scout"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-chapter02
  DOCKER_REGISTRY: docker.io
  DOCKER_USER: aerabi

permissions:
  id-token: write
  contents: read
  pull-requests: write
  packages: write
  checks: write

defaults:
  run:
    working-directory: chapter02

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: chapter02
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and export Docker image
        uses: docker/build-push-action@v5
        with:
          context: chapter02
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=docker,dest=${{ runner.temp }}/${{ env.IMAGE_NAME }}.tar

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.IMAGE_NAME }}
          path: ${{ runner.temp }}/${{ env.IMAGE_NAME }}.tar

  docker_scout_compare:
    runs-on: ubuntu-latest
    needs:
      - docker_build
    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.IMAGE_NAME }}
          path: ${{ runner.temp }}

      - name: Load Docker image
        run: |
          docker load -i ${{ runner.temp }}/${{ env.IMAGE_NAME }}.tar
          docker image ls -a

      - name: Log into Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Run Docker Scout to compare current image with the one in the registry
        uses: docker/scout-action@v1
        with:
          command: compare
          image: ${{ steps.meta.outputs.tags }}
          to: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          ignore-unchanged: true
          only-severities: critical,high
          github-token: '${{ github.token }}'

      - name: Run Docker Scout to extract vulnerabilities from the image
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ steps.meta.outputs.tags }}
          sarif-file: scout.sarif
          github-token: '${{ github.token }}'

      - name: Upload Docker Scout scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: scout.sarif
